"""rename user verified to confirmed

Revision ID: 3e3792be1a5d
Revises: 75b5158dc721
Create Date: 2021-07-24 20:50:16.254355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3792be1a5d'
down_revision = '75b5158dc721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('verified', new_column_name='confirmed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirmed', new_column_name='verified')


    # ### end Alembic commands ###
