"""add default to auth sequence

Revision ID: c66420fca7e2
Revises: 84551bf36b98
Create Date: 2021-08-13 20:55:31.547716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66420fca7e2'
down_revision = '84551bf36b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))
    op.execute("UPDATE auth_sequence SET is_default = true")
    with op.batch_alter_table('auth_sequence', schema=None) as batch_op:
        batch_op.alter_column('is_default', nullable=False)
    # ### end Alembic commands ###
    # Insert seed data
    auth_sequence_table = sa.table('auth_sequence',
        sa.column('name', sa.String),
        sa.column('enabled', sa.Boolean),
        sa.column('loa', sa.Integer),
        sa.column('is_default', sa.Boolean),
    )
    auth_methods_table = sa.table('auth_methods',
        sa.column('auth_sequence_id', sa.Integer),
        sa.column('auth_method_id', sa.Integer),
        sa.column('step', sa.Integer),
        sa.column('enabled', sa.Boolean),
    )
    op.bulk_insert(auth_sequence_table,
        [
            {'name':'Username only', 'loa': 0, 'is_default': False, 'enabled': True},
            {'name':'Username + mail', 'loa': 2, 'is_default': False, 'enabled': True},
            {'name':'Username + FIDO2 without PIN', 'loa': 2, 'is_default': True, 'enabled': True}
        ]
    )
    op.bulk_insert(auth_methods_table,
        [
            {'auth_sequence_id': 1, 'auth_method_id': 1, 'step': 1, 'enabled': True},
            {'auth_sequence_id': 2, 'auth_method_id': 1, 'step': 1, 'enabled': True},
            {'auth_sequence_id': 2, 'auth_method_id': 2, 'step': 2, 'enabled': True},
            {'auth_sequence_id': 3, 'auth_method_id': 1, 'step': 1, 'enabled': True},
            {'auth_sequence_id': 3, 'auth_method_id': 3, 'step': 4, 'enabled': True},

        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sequence', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
