"""add auth tables

Revision ID: 82325fe59e79
Revises: 3a86b5d2e473
Create Date: 2021-08-03 12:01:56.933201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82325fe59e79'
down_revision = '3a86b5d2e473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('auth_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('loa', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_methods',
    sa.Column('auth_sequence_id', sa.Integer(), nullable=False),
    sa.Column('auth_method_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auth_method_id'], ['auth_method.id'], ),
    sa.ForeignKeyConstraint(['auth_sequence_id'], ['auth_sequence.id'], ),
    sa.PrimaryKeyConstraint('auth_sequence_id', 'auth_method_id')
    )
    # ### end Alembic commands ###
    # Insert seed data
    auth_method_table = sa.table('auth_method',
        sa.column('name', sa.String),
        sa.column('is_enabled', sa.Boolean),
    )
    op.bulk_insert(auth_method_table,
        [
            {'name':'Username'},
            {'name':'Mail'},
            {'name':'FIDO2'}
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_methods')
    op.drop_table('auth_sequence')
    op.drop_table('auth_method')
    # ### end Alembic commands ###
