"""add fido2credential

Revision ID: 769f5cc333d2
Revises: 505ee6f0b279
Create Date: 2021-08-31 18:57:35.770316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769f5cc333d2'
down_revision = '505ee6f0b279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fido2credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attestation', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attestation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fido2credential')
    # ### end Alembic commands ###
