# coding=utf-8
import os

# API
API_URL = os.getenv('NOTH_API_URL')

# SESSION
SESSION_SECRET_KEY = os.getenv('NOTH_API_SESSION_SECRET_KEY')

# FIDO 2 RP CONFIG
FIDO2_NAME = os.getenv('NOTH_API_FIDO2_NAME')
FIDO2_RP = os.getenv('NOTH_API_FIDO2_RP')

# MAIL
MAIL_SENDER_NAME = os.getenv('NOTH_API_MAIL_SENDER_NAME')
MAIL_SENDER_EMAIL = os.getenv('NOTH_API_MAIL_SENDER_EMAIL')
MAIL_API_URL = os.getenv('NOTH_API_MAIL_API_URL')
MAIL_API_KEY = os.getenv('NOTH_API_MAIL_API_KEY')
MAIL_TOKEN_CONFIRM_SECRET = os.getenv('NOTH_API_MAIL_TOKEN_CONFIRM_SECRET')
MAIL_TOKEN_AUTHENTICATION_SECRET = os.getenv('NOTH_API_MAIL_TOKEN_AUTHENTICATION_SECRET')

