"""add otp code table

Revision ID: 254d6af91809
Revises: b03d71722b7d
Create Date: 2021-08-24 05:00:52.756710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254d6af91809'
down_revision = 'b03d71722b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_otp_code_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_code'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otp_code')
    # ### end Alembic commands ###
