"""remove user foreign key to authsequence

Revision ID: 7ed3e3c85119
Revises: 82325fe59e79
Create Date: 2021-08-04 04:36:12.159585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed3e3c85119'
down_revision = '82325fe59e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sequence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_auth_sequence_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_sequence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_auth_sequence_user_id_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
