"""add created_at to FIDO2Credential

Revision ID: 84551bf36b98
Revises: c951223c9812
Create Date: 2021-08-04 20:07:09.947116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84551bf36b98'
down_revision = 'c951223c9812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fido2credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE fido2credential SET created_at = NOW()")
    with op.batch_alter_table('fido2credential', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fido2credential', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
