"""add phone field to user

Revision ID: b03d71722b7d
Revises: 7ed3e3c85119
Create Date: 2021-08-18 06:36:51.725283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03d71722b7d'
down_revision = '7ed3e3c85119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sequence', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('phone', sa.Unicode(length=255), nullable=False))
    op.create_unique_constraint(op.f('uq_user_phone'), 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_phone'), 'user', type_='unique')
    op.drop_column('user', 'phone')
    op.drop_column('auth_sequence', 'is_default')
    # ### end Alembic commands ###
